name: Deploy to AWS Lightsail Containers

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-west-2  # Replace with your desired region
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Install or Update AWS CLI
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update

      - name: Authenticate AWS CLI with Lightsail
        run: aws lightsail push-container-image --region us-west-2 --service-name my-service --label v1 --image 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-repository:latest

      - name: Deploy to AWS Lightsail Containers
        run: aws lightsail create-container-service-deployment --region us-west-2 --service-name my-service --containers my-container
