name: Java CI with Gradle and Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Generate Dockerfile
      run: |
        echo "FROM openjdk:11-jdk" > Dockerfile
        echo "COPY . /app" >> Dockerfile
        echo "WORKDIR /app" >> Dockerfile
        echo "CMD ./gradlew bootRun" >> Dockerfile

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - uses : mr-smithers-excellent/docker-build-push@v4
      with:
       image: tahalc/test
       registry: docker.io
       username: ${{secrets.DOCKER_USERNAME}}
       password: ${{secrets.DOCKER_PASSWORD}}
