name: CI/CD

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode -DskipTests package

      - name: Prepare Docker image
        run: |
          mkdir staging
          cp target/*.jar staging
          cd staging
          echo 'FROM openjdk:17' >> Dockerfile
          echo 'COPY ./*.jar /app/app.jar' >> Dockerfile
          echo 'CMD ["java", "-jar", "/app/app.jar"]' >> Dockerfile

      - name: Build Docker image
        run: docker build -t aishootimage:latest staging

      - name: Configure AWS credentials
        run: |
          mkdir $HOME/.aws
          echo "[default]" >> $HOME/.aws/credentials
          echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> $HOME/.aws/credentials
          echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $HOME/.aws/credentials
          echo "[default]" >> $HOME/.aws/config
          echo "region = us-east-1" >> $HOME/.aws/config

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 665571210309.dkr.ecr.us-east-1.amazonaws.com

      - name: Tag Docker image
        run: |
          docker tag aishootimage:latest 665571210309.dkr.ecr.us-east-1.amazonaws.com/aishootimage:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 665571210309.dkr.ecr.us-east-1.amazonaws.com/aishootimage:latest
